package com.zlead.fplat.entity;

import java.io.Serializable;

public class OaAgentRevinfo implements Serializable {
    private Integer revId;//主键
    private Integer agentId;//代理商id
    private String revName;//收货人姓名
    private String revTel;//收货电话
    private String revProvince;//省
    private String revCity;//市
    private String revCounty;//区
    private String revAddr;//详细地址
    private String revDefault;//是否默认 是否默认（1:是;0:否）
    private Integer sysId;//店铺ID
    private Integer isFact;//是否工厂端创建  1.是 0.不是
    private Long memberAddrId;//关联t_member_address主键id

    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_agent_revinfo.rev_id
     *
     * @return the value of oa_agent_revinfo.rev_id
     *
     * @mbg.generated
     */
    public Integer getRevId() {
        return revId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_agent_revinfo.rev_id
     *
     * @param revId the value for oa_agent_revinfo.rev_id
     *
     * @mbg.generated
     */
    public void setRevId(Integer revId) {
        this.revId = revId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_agent_revinfo.agent_id
     *
     * @return the value of oa_agent_revinfo.agent_id
     *
     * @mbg.generated
     */
    public Integer getAgentId() {
        return agentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_agent_revinfo.agent_id
     *
     * @param agentId the value for oa_agent_revinfo.agent_id
     *
     * @mbg.generated
     */
    public void setAgentId(Integer agentId) {
        this.agentId = agentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_agent_revinfo.rev_name
     *
     * @return the value of oa_agent_revinfo.rev_name
     *
     * @mbg.generated
     */
    public String getRevName() {
        return revName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_agent_revinfo.rev_name
     *
     * @param revName the value for oa_agent_revinfo.rev_name
     *
     * @mbg.generated
     */
    public void setRevName(String revName) {
        this.revName = revName == null ? null : revName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_agent_revinfo.rev_tel
     *
     * @return the value of oa_agent_revinfo.rev_tel
     *
     * @mbg.generated
     */
    public String getRevTel() {
        return revTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_agent_revinfo.rev_tel
     *
     * @param revTel the value for oa_agent_revinfo.rev_tel
     *
     * @mbg.generated
     */
    public void setRevTel(String revTel) {
        this.revTel = revTel == null ? null : revTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_agent_revinfo.rev_province
     *
     * @return the value of oa_agent_revinfo.rev_province
     *
     * @mbg.generated
     */
    public String getRevProvince() {
        return revProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_agent_revinfo.rev_province
     *
     * @param revProvince the value for oa_agent_revinfo.rev_province
     *
     * @mbg.generated
     */
    public void setRevProvince(String revProvince) {
        this.revProvince = revProvince == null ? null : revProvince.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_agent_revinfo.rev_city
     *
     * @return the value of oa_agent_revinfo.rev_city
     *
     * @mbg.generated
     */
    public String getRevCity() {
        return revCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_agent_revinfo.rev_city
     *
     * @param revCity the value for oa_agent_revinfo.rev_city
     *
     * @mbg.generated
     */
    public void setRevCity(String revCity) {
        this.revCity = revCity == null ? null : revCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_agent_revinfo.rev_county
     *
     * @return the value of oa_agent_revinfo.rev_county
     *
     * @mbg.generated
     */
    public String getRevCounty() {
        return revCounty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_agent_revinfo.rev_county
     *
     * @param revCounty the value for oa_agent_revinfo.rev_county
     *
     * @mbg.generated
     */
    public void setRevCounty(String revCounty) {
        this.revCounty = revCounty == null ? null : revCounty.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_agent_revinfo.rev_addr
     *
     * @return the value of oa_agent_revinfo.rev_addr
     *
     * @mbg.generated
     */
    public String getRevAddr() {
        return revAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_agent_revinfo.rev_addr
     *
     * @param revAddr the value for oa_agent_revinfo.rev_addr
     *
     * @mbg.generated
     */
    public void setRevAddr(String revAddr) {
        this.revAddr = revAddr == null ? null : revAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_agent_revinfo.rev_default
     *
     * @return the value of oa_agent_revinfo.rev_default
     *
     * @mbg.generated
     */
    public String getRevDefault() {
        return revDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_agent_revinfo.rev_default
     *
     * @param revDefault the value for oa_agent_revinfo.rev_default
     *
     * @mbg.generated
     */
    public void setRevDefault(String revDefault) {
        this.revDefault = revDefault == null ? null : revDefault.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_agent_revinfo.sys_id
     *
     * @return the value of oa_agent_revinfo.sys_id
     *
     * @mbg.generated
     */
    public Integer getSysId() {
        return sysId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_agent_revinfo.sys_id
     *
     * @param sysId the value for oa_agent_revinfo.sys_id
     *
     * @mbg.generated
     */
    public void setSysId(Integer sysId) {
        this.sysId = sysId;
    }

    public Integer getIsFact() {
        return isFact;
    }

    public void setIsFact(Integer isFact) {
        this.isFact = isFact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_agent_revinfo.member_addr_id
     *
     * @return the value of oa_agent_revinfo.member_addr_id
     *
     * @mbg.generated
     */
    public Long getMemberAddrId() {
        return memberAddrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_agent_revinfo.member_addr_id
     *
     * @param memberAddrId the value for oa_agent_revinfo.member_addr_id
     *
     * @mbg.generated
     */
    public void setMemberAddrId(Long memberAddrId) {
        this.memberAddrId = memberAddrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_agent_revinfo
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        OaAgentRevinfo other = (OaAgentRevinfo) that;
        return (this.getRevId() == null ? other.getRevId() == null : this.getRevId().equals(other.getRevId()))
            && (this.getAgentId() == null ? other.getAgentId() == null : this.getAgentId().equals(other.getAgentId()))
            && (this.getRevName() == null ? other.getRevName() == null : this.getRevName().equals(other.getRevName()))
            && (this.getRevTel() == null ? other.getRevTel() == null : this.getRevTel().equals(other.getRevTel()))
            && (this.getRevProvince() == null ? other.getRevProvince() == null : this.getRevProvince().equals(other.getRevProvince()))
            && (this.getRevCity() == null ? other.getRevCity() == null : this.getRevCity().equals(other.getRevCity()))
            && (this.getRevCounty() == null ? other.getRevCounty() == null : this.getRevCounty().equals(other.getRevCounty()))
            && (this.getRevAddr() == null ? other.getRevAddr() == null : this.getRevAddr().equals(other.getRevAddr()))
            && (this.getRevDefault() == null ? other.getRevDefault() == null : this.getRevDefault().equals(other.getRevDefault()))
            && (this.getSysId() == null ? other.getSysId() == null : this.getSysId().equals(other.getSysId()))
            && (this.getIsFact() == null ? other.getIsFact() == null : this.getIsFact().equals(other.getIsFact()))
            && (this.getMemberAddrId() == null ? other.getMemberAddrId() == null : this.getMemberAddrId().equals(other.getMemberAddrId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_agent_revinfo
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getRevId() == null) ? 0 : getRevId().hashCode());
        result = prime * result + ((getAgentId() == null) ? 0 : getAgentId().hashCode());
        result = prime * result + ((getRevName() == null) ? 0 : getRevName().hashCode());
        result = prime * result + ((getRevTel() == null) ? 0 : getRevTel().hashCode());
        result = prime * result + ((getRevProvince() == null) ? 0 : getRevProvince().hashCode());
        result = prime * result + ((getRevCity() == null) ? 0 : getRevCity().hashCode());
        result = prime * result + ((getRevCounty() == null) ? 0 : getRevCounty().hashCode());
        result = prime * result + ((getRevAddr() == null) ? 0 : getRevAddr().hashCode());
        result = prime * result + ((getRevDefault() == null) ? 0 : getRevDefault().hashCode());
        result = prime * result + ((getSysId() == null) ? 0 : getSysId().hashCode());
        result = prime * result + ((getIsFact() == null) ? 0 : getIsFact().hashCode());
        result = prime * result + ((getMemberAddrId() == null) ? 0 : getMemberAddrId().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_agent_revinfo
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", revId=").append(revId);
        sb.append(", agentId=").append(agentId);
        sb.append(", revName=").append(revName);
        sb.append(", revTel=").append(revTel);
        sb.append(", revProvince=").append(revProvince);
        sb.append(", revCity=").append(revCity);
        sb.append(", revCounty=").append(revCounty);
        sb.append(", revAddr=").append(revAddr);
        sb.append(", revDefault=").append(revDefault);
        sb.append(", sysId=").append(sysId);
        sb.append(", isFact=").append(isFact);
        sb.append(", memberAddrId=").append(memberAddrId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}